### ISSUE TITLE
robotarm_random.py don't have a dg

### ISSUE THREAD

**Issue by glasslucas00** [wanxinjin/Learning-from-Sparse-Demonstrations#4]
It should be a g;
so I change  env.initDyn(l1=1, m1=1, l2=1, m2=1, dg=0) to  env.initDyn(l1=1, m1=1, l2=1, m2=1, g=0) and it works

**Comment by wanxinjin** [comment]
Thank you, @glasslucas00, for reporting this bug. I have just fixed it.
https://github.com/wanxinjin/Learning-from-Sparse-Demonstrations/blob/master/Examples/robotarm_random.py

thank you for your interest in this work.
